### ISSUE TITLE
Curlify error

### ISSUE THREAD

**Issue by holdestmade** [Pyhive/HA-Hive-Custom-Component#1]
When trying to add the 2020.1_b1 version in the integrations UI, get this in the log:

`Error occurred loading configuration flow for integration hive: No module named 'curlify'`

**Comment by KJonline** [comment]
@holdestmade thanks for the feedback and highlighting the issue, I haven't announced this change as this is only the first beta. We will be looking at recruiting some testers soon. As I don’t own all the device types we support in home assistant. I was hoping people wouldn’t have show beta versions selected, but it looks like you have.

**Comment by holdestmade** [comment]
OK, thanks. I think it actually caused a segfault (may be coincidental). 
I coudn't find a way to go back to a previous version in HACS (HACS used to have a drop down to select a version) so had to uninstall it from HACS, restart and then reinstall the 2019 version. All back working now

**Comment by KJonline** [comment]
@holdestmade glad you got back to the previous version.

**Comment by KJonline** [comment]
fixed in latest beta
