### ISSUE TITLE
Hive Unavailable

### ISSUE THREAD

**Issue by leacho73** [Pyhive/HA-Hive-Custom-Component#11]
Hi,

My Hive system is showing unavailable since 19th October? My hive thermostat is just showing unavailable - I've pulled the latest code, but still nothing.

Home Assistant is only showing the following error:
2020-10-19 12:03:33 WARNING (MainThread) [homeassistant.setup] Setup of hive is taking over 10 seconds.

Have checked creds are all ok. Are there any other logs I can check?

Thanks

**Comment by KJonline** [comment]
@leacho73 is this still an issue for you?

**Comment by leacho73** [comment]
Hi @KJonline - I managed to get it working again by changing the following in manifest.json:

 "requirements": ["pyhiveapi==0.2.19.5"],

Any other value didn't work for me I am afraid
