### ISSUE TITLE
2020.1_b10: Token expiring?

### ISSUE THREAD

**Issue by CaptInsano** [Pyhive/HA-Hive-Custom-Component#13]
Login and devices were working at first with b10 but after a period of time (not sure how long) thermostats stopped updating with b10, I restarted the homeassistant server in an attempt to fix and got the following error:

```
Logger: homeassistant.config_entries
Source: custom_components/hive/__init__.py:158
First occurred: 10:23:02 PM (1 occurrences)
Last logged: 10:23:02 PM

Error setting up entry XXXXXXXXXXXXXXX@gmail.com for hive
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 234, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/hive/__init__.py", line 158, in async_setup_entry
    devices = await hive.session.start_session(Tokens,
  File "/usr/local/lib/python3.8/site-packages/pyhiveapi/hive_session.py", line 346, in start_session
    await self.get_devices("No_ID")
  File "/usr/local/lib/python3.8/site-packages/pyhiveapi/hive_session.py", line 177, in get_devices
    await self.hive_refresh_tokens()
  File "/usr/local/lib/python3.8/site-packages/pyhiveapi/hive_session.py", line 123, in hive_refresh_tokens
    resp_p = await self.hive.refresh_tokens(Data.s_tokens)
TypeError: refresh_tokens() takes 1 positional argument but 2 were given
```

Now all entities are appearing as "Unavailable".

Hope this helps in debugging

**Comment by KJonline** [comment]
@CaptInsano this should be fixed in beta 11, please update and restart

**Comment by CaptInsano** [comment]
You are on fire tonight!!

I updated, I had to delete and re-add the integration and sign up again. I will let you know if it stops updating again:

Just some notes: 
1. beta 11 does not list the hub as a device under integrations as per prev versions (not sure if this is intended).

2. the thermostats are no longer appearing as climate devices so my thermostat cards are all now broken:

"Entity not available: climate.ground_floor" "Entity not available: climate.1st_floor" "Entity not available: climate.2nd_floor"


The devices appear like the following under entities (pasted here as plaintext):
```
Name
Entity ID
Integration
Status

1st Floor Boost
sensor.1st_floor_boost
Hive

1st Floor Current Temperature
sensor.1st_floor_current_temperature
Hive

1st Floor Mode
sensor.1st_floor_mode
Hive

1st Floor State
sensor.1st_floor_state
Hive

1st Floor Target Temperature
sensor.1st_floor_target_temperature
Hive

2nd Floor Boost
sensor.2nd_floor_boost
Hive

2nd Floor Current Temperature
sensor.2nd_floor_current_temperature
Hive

2nd Floor Mode
sensor.2nd_floor_mode
Hive

2nd Floor State
sensor.2nd_floor_state
Hive

2nd Floor Target Temperature
sensor.2nd_floor_target_temperature
Hive

Boost Hot Water
switch.boost_hot_water
Hive

Ground Floor Boost
sensor.ground_floor_boost
Hive

Ground Floor Boost
sensor.ground_floor_boost_2
Hive

Ground Floor Current Temperature
sensor.ground_floor_current_temperature
Hive

Ground Floor Mode
sensor.ground_floor_mode
Hive

Ground Floor Mode
sensor.ground_floor_mode_2
Hive
```

**Comment by CaptInsano** [comment]
I mean it dev, you are on fire!

I have updated to beta 14,:

from above:
1. Hub is back in device
2. Devices appear as climate.device_name again!
3. battery level is back!

however when I try to change temp from the thermostat, nothing happens and I get the following error in homeassistant log:

`2020-11-05 23:22:00 ERROR (MainThread) [pyhiveapi.custom_logging] ERROR - Received 400 response from API.`


NOTE:
I know the original reason for this issue is solved but I don't want to spam the repo with issue tickets. Please let me know what you prefer me to do for reporting issues.

**Comment by KJonline** [comment]
@CaptInsano yep already on that one now just found he cause of the issue race condition
