### ISSUE TITLE
Two factor authentication with hive

### ISSUE THREAD

**Issue by nomisllens** [Pyhive/HA-Hive-Custom-Component#14]
HI Hive have now forced two factor authentication and a code is sent to my mbile phone, i do not suppose there is anyway around this?

**Comment by CaptInsano** [comment]
Update to latest beta (b15 at time of writing), 
remove all hive related settings from configuration.yaml,
set up hive component via integrations UI and 2FA works

**Comment by nomisllens** [comment]
installed b15 ok but do not see a config method other than the .yaml file ?

**Comment by CaptInsano** [comment]
Install b15 from HACs, remove config from configurations.yaml then make sure to restart HomeAssistant.

Then:
Configuration > Integrations > Add (+) > Search for Hive

**Comment by nomisllens** [comment]
Thanks,
Installed b15 from hacs, removed configuration from .yaml rebooted but in configuration>integrations>Add+ no Hive is listed at all

**Comment by nomisllens** [comment]
it finally appeared on it own
