### ISSUE TITLE
Component isn't doing anything

### ISSUE THREAD

**Issue by afk11** [Pyhive/HA-Hive-Custom-Component#15]
Hi,
I tried out the normal hive integration with HA, and setup my config, and restarted but it doesn't seem to do anything. I have the heating + thermostat

I've since setup HACS and installed the '2020.0' version from this repo, but I get the same result.

I grabbed the 'hivecli' go executable and to try and list devices using my credentials, and that actually worked

Any suggestions where to go from here?

 - Checked config/info, and saw the 'hive' integration listed
 - Checked the logs after enabling debug

Home Assistant 0.117.4
'pyhiveapi==0.2.19.5'

```
2020-11-06 17:15:32 INFO (MainThread) [homeassistant.bootstrap] Setting up stage 2: {'group', 'mqtt', 'hive', 'logbook', 'default_config', 'input_select', 'automation', 'tts', 'plex', 'met', 'system_health', 'history', 'sun', 'timer', 'media_source', 'tag', 'hacs', 'input_number', 'dyson', 'persistent_notification', 'counter', 'scene', 'input_text', 'map', 'ssdp', 'deconz', 'updater', 'script', 'zone', 'input_datetime', 'zeroconf', 'input_boolean', 'mobile_app'}
2020-11-06 17:15:32 INFO (MainThread) [homeassistant.setup] Setting up hive
```

```
2020-11-06 17:15:35 INFO (MainThread) [homeassistant.setup] Setup of domain hive took 3.4 seconds
2020-11-06 17:15:35 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event component_loaded[L]: component=hive>
2020-11-06 17:15:35 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection.140117716929600] Sending {"id": 3, "type": "event", "event": {"event_type": "component_loaded", "data": {"component": "hive"}, "origin": "LOCAL", "time_fired": "2020-11-06T17:15:35.440224+00:00", "context": {"id": "trimmed", "parent_id": null, "user_id": null}}}
2020-11-06 17:15:35 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection.140117716929600] Sending {"id": 9, "type": "event", "event": {"event_type": "component_loaded", "data": {"component": "hive"}, "origin": "LOCAL", "time_fired": "2020-11-06T17:15:35.440224+00:00", "context": {"id": "trimmed "parent_id": null, "user_id": null}}}
```

The last logs to mention hive are:
```
2020-11-06 17:15:37 DEBUG (MainThread) [custom_components.hacs.repository.integration.Pyhive.HA-Hive-Custom-Component] Getting repository information
2020-11-06 17:15:37 DEBUG (MainThread) [custom_components.hacs.repository.integration.Pyhive.HA-Hive-Custom-Component] Running checks against 2020.0
```

**Comment by KJonline** [comment]
@afk11 

It seems your not using the latest version of the pyhiveapi it’s be pyhiveapi 0.2.20.2 for it to work

**Comment by afk11** [comment]
@KJonline ok! I see 2020.0 still points to v0.2.19.5 but I guess a new release will fix it? I can probably tweak it on the filesystem directly, is there anything I need to do to get it to refresh or just restart HA?

**Comment by KJonline** [comment]
@afk11  thanks for spotting that I have update the 2020 release now and redistributed of you reinstall 2020 again it should install the correct pyhiveapi version

**Comment by afk11** [comment]
Brilliant, thanks a lot! I tried it out and see the new version was downloaded. Weirdly it's not doing anything still.

I've setup a venv to try the library, and set my details in the example. When I run it it doesn't show any devices.. though I tried the golang hivecli application and it was able to see 1 heating zone

Stepping through the code now, I see initialise_api calls hive_api_logon, wherever HSC.session_id is None so it doesn't update nodes.. The authentication call returns my `personal info, platform, endpoint, alerts, status, refreshToken, accessToken`

Will update if I get any further

**Comment by afk11** [comment]
Went debugging, I'm getting no session id in the example because of this check https://github.com/Pyhive/Pyhiveapi/blob/master/pyhiveapi/pyhiveapi.py#L333

**Comment by KJonline** [comment]
Is your postcode not in the result from login?

**Comment by afk11** [comment]
I'm in Ireland, so maybe the response object is different? Here's the keys in the users object (stripped out values)

{'user': {'id': '...', 'username': '...', 'firstName': '', 'lastName': '', 'address': '', 'city': '', 'country': '', 'countryCode': '', 'longitude': 0.0, 'latitude': 0.0, 'email': '', 'mobile': '', 'phone': '', 'timezone': '', 'locale': '', 'temperatureUnit': ''}

**Comment by afk11** [comment]
We posted at the same time :) Nope, there's no key for that. I haven't been able to find a way to update any details on the hive website, but it has a correct 'address' and 'city'

I see it's being used for the weather request later

**Comment by KJonline** [comment]
@afk11 so the reason we check for the postcode is because use it when making an api call to hives weather api. When you look at your heating device in the hive app is there a weather icon in there?

**Comment by afk11** [comment]
Hmm not that I can see. On home (the thing with the hexagon with heating in the middle) there's nothing
If I go click the heating device icon, it goes to Zone 1. There's an ice logo with protect beside it, a house icon with the temperature, and a boost icon

**Comment by afk11** [comment]
On 6 Nov 2020 21:33, Khole <notifications@github.com> wrote:
@afk11 so the reason we check for the postcode is because use it when making an api call to hives weather api. When you look at your heating device in the hive app is there a weather icon in there?

**Comment by KJonline** [comment]
@afk11 ye you are right the weather status has gone from the heating device and is no longer present something I haven’t checked before. The api must still be working even though they have taken it out. Hmm so I could take it out of the library in the next upgrade. 

For yourself there is 2 options manually modify your setup to bypass the weather functionality or upgrade to the beta version and see how you get on. The beta version does have bugs though and I can’t say what will and will not work depending by on your setup.

**Comment by afk11** [comment]
I'll try patching out the postcode and weather check and report back, thanks!

**Comment by afk11** [comment]
That worked! I commented out the postcode check and any places where the weather was updated and it's detecting devices now on HA! thanks a million

Is it a regional thing do you reckon, or did yours also lose the weather icon?

**Comment by KJonline** [comment]
@afk11 

I am using the new beta which is a complete rewrite so I didn’t face this issue. But I have also lost the weather temp from my hive app and I am in the mainland uk

**Comment by afk11** [comment]
Thanks @KJonline. I suppose, maybe leave the if 'postcode' in ... part, but drop the else part?

Then maybe in `hiveapi_get_weather`, or done by the caller: check if the postcode is the empty string, if so, don't request weather

Maybe they'll add it back - in that case a release adding it back wouldn't be necessary

**Comment by afk11** [comment]
Hi @KJonline - I opened a PR for this on the Pyhiveapi repo as there have been a few HA updates, and if I install them it nukes my changes https://github.com/Pyhive/Pyhiveapi/pull/4
