### ISSUE TITLE
b20: Integration needs to be reconfigured but does not succeed

### ISSUE THREAD

**Issue by CaptInsano** [Pyhive/HA-Hive-Custom-Component#19]
updated to b20, restarted and got the following error:

![image](https://user-images.githubusercontent.com/332478/99444224-d46d9180-2913-11eb-8542-75159584942c.png)

When I try to re-enter my email and password I just get the error:

"unknown error occured"

I completely uninstalled the integration and reinstalled to try and configure but it still does not work.

The following appears in homeassistant log

```
2020-11-17 20:28:43 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry mrcathaloshea@gmail.com for hive
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 234, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/hive/__init__.py", line 181, in async_setup_entry
    devicelist = devices.get(component)
AttributeError: 'str' object has no attribute 'get'
```

**Comment by KJonline** [comment]
I would roll back to b19 for now hive is having service problems atm the app won’t even update I’ll remove beta 20 from Hacs

**Comment by CaptInsano** [comment]
Ahh! That explains a lot. I have downgraded but cannot get logged in on b19 either!

Issue closed as not related to integration!
