### ISSUE TITLE
2020.1_b21 Config flow assumes 2fa enabled, preventing HA from starting

### ISSUE THREAD

**Issue by jonathandann** [Pyhive/HA-Hive-Custom-Component#20]
I'm upgrading via hacs to 2020.1_b21. It looks like the component is trying to go some 2fa-related config flow and failing. This causes HA startup to take a long time while HA waits for the hive component to complete.

I don't have 2fa set up yet (b/c I didn't know it was supported). Here's the error:

`2020-11-25 09:44:29 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 130, in async_init
result = await self._async_handle_step(
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 213, in _async_handle_step
result: Dict = await getattr(flow, method)(user_input)
File "/config/custom_components/hive/config_flow.py", line 169, in async_step_import
return await self.async_step_finish()
File "/config/custom_components/hive/config_flow.py", line 124, in async_step_finish
self.data["tokens"] = self.tokens.get(
AttributeError: 'NoneType' object has no attribute 'get'`

And here's the code that's getting `None`:

`    async def async_step_finish(self, user_input=None):
        """Finish setup and create the config entry."""
        self.data["tokens"] = self.tokens.get(
            "AuthenticationResult", "ERROR")

        if "AccessToken" in self.data["tokens"]:
            # Setup the config entry
            self.data.update({"created": str(datetime.now())})

            return self.async_create_entry(
                title=self.data["username"],
                data=self.data
            )
        else:
            return self.async_abort(reason="unknown")`

Looks like `self.tokens` is `None`.

**Comment by KJonline** [comment]
@jonathandann Thanks for highlighting this it seems to be an oversight I have missed in a recent change just an incorrect variable name. The integration should still work setting it up through the home assistant UI.

**Comment by jonathandann** [comment]
@KJonline Thanks for the update. Probably a dumb question, but how do I go about setting it up own the UI if it's already installed? Just uninstall the integration and start over?

**Comment by jonathandann** [comment]
@KJonline I've answered my own question by just trying it. Sorry for the noise.

**Comment by KJonline** [comment]
@jonathandann, Yes if you remove your config from your configuration file, restart home assistant, and then use the home assistant integrations panel to set it back up.
