### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by CJA59UK** [Pyhive/HA-Hive-Custom-Component#23]
Hi I have just updated to Home Assistant 0.118.4 and have lost all of my Hive devices/entities. I have tried taking out the details in the configuration.yaml and then re-adding them, reinstalling the integration via HACS. Also the two factor authentification needs sorting out - I have turned it off

**Comment by elyobelyob** [comment]
Already opened (& solved) here .. https://github.com/Pyhive/HA-Hive-Custom-Component/issues/22

**Comment by KJonline** [comment]
Closing Issues Address in #22
