### ISSUE TITLE
Motion sensors permanently 'on'

### ISSUE THREAD

**Issue by perjury** [Pyhive/HA-Hive-Custom-Component#24]
All my Hive motion sensors are showing motion 'detected' - sensor is 'on' all the time

Not seeing any errors in the log.
No changes to configuration other than changing to beta version to get system working again.
Curiously, they show State Changed 17-11-2020

**Comment by mansbo** [comment]
I'm getting that too since installing the beta version today.  I have a number of motion sensors and they are all 'on' all the time.  They have a mixture of State Changed dates but they are all back in November.

**Comment by KJonline** [comment]
@mansbo, @perjury Please can you retest this with the new beta 2020.1_b22

**Comment by mansbo** [comment]
Updated to 2020.1_b22 and my motion sensors are now working normally - thanks for the speedy response!

**Comment by perjury** [comment]
Updated to 2020.1_b22 and my motion sensors now appear to be working normally. But getting 'unavailable' for many of the additional sensors. Will file a separate report.
Thanks for the speedy response
