### ISSUE TITLE
Updated to 2020.1_b22 - additional sensors 'unavailable'

### ISSUE THREAD

**Issue by perjury** [Pyhive/HA-Hive-Custom-Component#25]
![developer_tools-Home-Assistant](https://user-images.githubusercontent.com/11613248/101089772-88764a00-35ad-11eb-85eb-d31d6afd3406.png)

**Comment by perjury** [comment]
Also, 
water_heater.hot_water | unavailable

**Comment by perjury** [comment]
Error in Log for water heater
Logger: homeassistant.components.water_heater
Source: custom_components/hive/water_heater.py:109
Integration: Water Heater (documentation, issues)
First occurred: 20:47:56 (1 occurrences)
Last logged: 20:47:56

hive: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 359, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 466, in async_device_update
    await task
  File "/config/custom_components/hive/water_heater.py", line 109, in async_update
    self.device = await self.hive.hotwater.get_hotwater(self.device)
  File "/usr/local/lib/python3.8/site-packages/pyhiveapi/hotwater.py", line 50, in get_hotwater
    "Device update {0}", info=device['status'])
KeyError: 'status'

**Comment by perjury** [comment]
And lights

Logger: homeassistant.components.light
Source: custom_components/hive/light.py:55
Integration: Light (documentation, issues)
First occurred: 20:47:56 (2 occurrences)
Last logged: 20:47:56

Error adding entities for domain light with platform hive
Error while setting up hive platform for light
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 316, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 384, in _async_add_entity
    device_info = entity.device_info
  File "/config/custom_components/hive/light.py", line 55, in device_info
    "model": self.device["device_data"]["model"],
KeyError: 'model'

**Comment by mansbo** [comment]
Same here.  I've gone back to the previous beta to confirm everything was fine - it was.  So something in the latest beta.

**Comment by KJonline** [comment]
@perjury What bulb type do you have or what type of the bulb is the one reporting the error. My guess its a colour bulb as I have a normal bulb and a colour temp bulb?

**Comment by perjury** [comment]
How do I revert to previuous beta using HACS

**Comment by KJonline** [comment]
If you go into HACS you should be able to click the versions and it will present a list the previous version should be in there

**Comment by perjury** [comment]
I don't have any colour bulbs. I think the ones throwing the error are normal (non colour temp) bulbs

**Comment by KJonline** [comment]
that weird as i have 4 of the normal ones and I don't seem to be getting that issue.

**Comment by perjury** [comment]
Ah - versions is under reinstall. Gotcha

**Comment by KJonline** [comment]
With the update to Beta 22 are you still configuring via the UI or have you changed back to the YAML config?

**Comment by perjury** [comment]
Via the UI

**Comment by KJonline** [comment]
@perjury I found the hot water issue, thanks for that. the light is a very strange one how can we have the same device yet it works for me and not yourself running the same code.

**Comment by captaindaveman** [comment]
I had the same issue, additional sensors on climate were unavailable, I've downgraded and it's back again

**Comment by perjury** [comment]
I wonder if the light issue might be that those lights were offline at the time I restarted HA?

**Comment by KJonline** [comment]
That shouldn't make a difference as i have a light offline now and if I restart HA I don't get the error.

**Comment by mansbo** [comment]
Not sure if this is a complete coincidence, but starting with 2020.1_b21 installed, I deleted the integration completely, updated to 2020.1_b22, restarted HA, added the integration through the UI and then restarted HA again.  I'm still getting the error regarding the hot water, but everything else now seems to be working fine.  I seem to end up with less entities under 2020.1_b22 than I did with 2020.1_b21, but I'm not missing anything vital so I'm not too bothered.

Thanks again for all your help.

**Comment by Corneloues** [comment]
I too have a bunch of sensors missing, but these are the core heating/hot water sensors. Also the Hub Status sensor changed its name too, but I got that one working.

I switched to beta because of the Hive auth issue.

I'm missing:

- water_heater.hot_water
- sensor.hot_water_boost
- sensor.hot_water_mode
- sensor.hot_water_state

- sensor.heating_boost
- sensor.heating_mode
- sensor.heating_state

Cheers,

Roy

**Comment by mansbo** [comment]
For me the 'unavailable' sensors are all the ones created by choosing "Add additional sensors" when setting up the integration through the UI.  I have been having a play around, and I'm pretty certain the setting for "Add additional sensors" does not persist after you have changed something via the "Options" button on the integration, e.g. to turn on debug or change the scan interval.  After the next HA restart, the additional sensors are all 'unavailable'.  Deleting the integration and setting it up again, they all come back.  So the workaround for me is to delete the integration, set it up again and then remember not to change any of the options.

**Comment by KJonline** [comment]
@mansbo thanks for identifying I’ll replicate and fix

**Comment by KJonline** [comment]
Fix released in Beta 23
