### ISSUE TITLE
ENtity picture overriding icons for switch entities

### ISSUE THREAD

**Issue by perjury** [Pyhive/HA-Hive-Custom-Component#26]
![image](https://user-images.githubusercontent.com/11613248/101092228-3800eb80-35b1-11eb-9c55-26c20f16b8ce.png)

**Comment by KJonline** [comment]
@perjury This is something i put into the latest beta would you prefer this or prefer to choose your own icon?

**Comment by perjury** [comment]
Definitely prefer to choose own icon please

**Comment by KJonline** [comment]
Fix released in Beta 23
