### ISSUE TITLE
 sensors not mirroring heating zone attribute values

### ISSUE THREAD

**Issue by perjury** [Pyhive/HA-Hive-Custom-Component#33]
sensor.ZONE_current_temperature and
sensor.ZONE_target_temperature

are not mirroring attributes of climate entity

**Screenshots**
![image](https://user-images.githubusercontent.com/11613248/101266645-c196f180-3748-11eb-8f11-42464f5c1fcc.png)
![image](https://user-images.githubusercontent.com/11613248/101266665-e4290a80-3748-11eb-83f6-5d10adb49f8d.png)
![image](https://user-images.githubusercontent.com/11613248/101266673-0a4eaa80-3749-11eb-8a87-78de8c099cb5.png)

**Comment by perjury** [comment]
Version beta 25

**Comment by perjury** [comment]
Workaround - remove any light groups used in the Hive App

**Comment by KJonline** [comment]
Fixed with latest release please reopen if still an issue
