### ISSUE TITLE
b25 - lights not reporting correctly

### ISSUE THREAD

**Issue by perjury** [Pyhive/HA-Hive-Custom-Component#34]
Lightbulb sensor showing online when it is in fact offline
e.g. Dining Room Lamp
Lightbulb showing state on when it is in fact off
e.g. Hall lamp
Lightbulb showing state off when it is in fact on
e.g. Living Room 1

**Screenshots**
![image](https://user-images.githubusercontent.com/11613248/101277516-eae96900-37ac-11eb-9880-b7acb01447ce.png)
![image](https://user-images.githubusercontent.com/11613248/101277541-18361700-37ad-11eb-8946-cbe83eb8614c.png)
![image](https://user-images.githubusercontent.com/11613248/101277572-4287d480-37ad-11eb-9568-59cba89f13ff.png)

Version beta 25

**Comment by KJonline** [comment]
@perjury what is your can interval set to? Obviously HA is updated default every 120seconds in your tests are you specifically testing this or have just noticed from casually using HA?

**Comment by perjury** [comment]
Scan interval 30 sec. Just noticed it while working on a dashboard . Not testing for it specifically

**Comment by keviny1273** [comment]
I have the same issue. My refresh internal is the default 120 seconds. I have a shed load of lights in the lounge (15 in total) and I noticed if I turn them off, HA shows them as still being on. This can happen for a reasonable period of time (at least 30 minutes). Also the same for some of the sensors such as the boost status. 

![image](https://user-images.githubusercontent.com/23584226/101281403-9357f700-37c6-11eb-9e6c-02ebfa7e8c8a.png)

Here is the hive status (from the web)
![image](https://user-images.githubusercontent.com/23584226/101281440-c306ff00-37c6-11eb-824b-318dbbaeb74f.png)

The boost finished at least an hour ago. 

Also the Current / Target Temperature is not updating.

![image](https://user-images.githubusercontent.com/23584226/101281469-f184da00-37c6-11eb-9b77-2512c3f0778e.png)

The above image shows on the right the entities are static (including the boost ends in time) but the Thermostat Card Configuration updates correctly.

Let us know if we can do anything to assist.

**Comment by keviny1273** [comment]
Some errors in the event log also seen. These are detailed here https://community.home-assistant.io/t/hive-integration/17374/868. I see these too.

**Comment by nil-ghosh** [comment]
Also noticed this error when HA is started.

Logger: pyhiveapi.custom_logging
Source: /srv/homeassistant/lib/python3.9/site-packages/pyhiveapi/custom_logging.py:83
First occurred: 1:58:44 PM (2 occurrences)
Last logged: 1:58:44 PM

ERROR - No data found for device - Hallway
ERROR - No data found for device - Study Room

**Comment by tmoore22** [comment]
same issue here on b25; heating is updating correctly, but Lights do not update from Hive status....

These errors appear at boot/restart of home assistant, these No data found ERROR are reported here for Hive groups (lights)

2020-12-25 01:32:07 ERROR (MainThread) [pyhiveapi.custom_logging] ERROR - No data found for device - Bedside Lights
2020-12-25 01:32:07 ERROR (MainThread) [pyhiveapi.custom_logging] ERROR - No data found for device - Hall Lights
2020-12-25 01:32:07 ERROR (MainThread) [pyhiveapi.custom_logging] ERROR - No data found for device - Kitchen Lights
2020-12-25 01:32:07 ERROR (MainThread) [homeassistant.components.light] Error adding entities for domain light with platform hive
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 316, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 384, in _async_add_entity
device_info = entity.device_info
File "/config/custom_components/hive/light.py", line 55, in device_info
"model": self.device["device_data"]["model"],
KeyError: 'model'
2020-12-25 01:32:07 ERROR (MainThread) [homeassistant.components.light] Error while setting up hive platform for light
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 207, in _async_setup_platform
await asyncio.gather(*pending)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 316, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 384, in _async_add_entity
device_info = entity.device_info
File "/config/custom_components/hive/light.py", line 55, in device_info
"model": self.device["device_data"]["model"],
KeyError: 'model'

some guidance to resolve would be appreciated!

**Comment by KJonline** [comment]
@tmoore22 just to test something. Would it be possible to ungroup the lights in Hive and restart HA and see if you get the same issues on a restart?

**Comment by keviny1273** [comment]
@KJonline i have removed the three Light Groups I had in Hive and I can confirm the lights and the other items listed in issue #33 are now updating and in sync. The errors seem to have gone as well.
Thanks Kevin

**Comment by KJonline** [comment]
@keviny1273 thanks a lot for testing that and confirming, I had a look at the code and found the groups to be a possible issue. Unfortunately currently we don’t support grouped lights. Looking into to it now though it should be possible in the future. For the time being I will put some code in to handle groups, so they can exist in the hive app but not in HA (yet)

**Comment by perjury** [comment]
I can confirm that my testing also shows that removing light groups from the Hive App is a workaround for this issue, #33  and #49

**Comment by perjury** [comment]
I spoke too soon.
Some of my offline -off at the switch - lights are now reporting as 'on' when they should be reporting as 'unavailable'.

**Comment by KJonline** [comment]
@perjury im guessing you have left it for 2 minutes for the data to update?

**Comment by perjury** [comment]
What seems to be happening is, if I start/re-start HA while the lights are off at the switch, they are correctly reported as offline.
If I then turn them on at the switch, they get reported as available and on.
If I then turn them off at the switch they stay as available and on in HA even though they are showing in the Hive app as offline.

**Comment by KJonline** [comment]
@perjury are you also checking the hive app at the same time to see if that is correct. What’s happens when a device goes offline is there is period of time before the hive cloud server is updated and then the HA interval added on top of that. For example if you have a light online and that shows in the hive app then change it to be offline the hive app doesn’t update straight away to show it offline.

**Comment by perjury** [comment]
The Hive app takes quite a long time to update - about 10 minutes maybe, I didn't time it.
But it's been several hours now since the dining room lights were turned off and they are still showing as online and on in HA.

**Comment by tmoore22** [comment]
same here, after a restart of HA; all status of lights shows correct, but then any subsequent changes on Hive are not updated in HA... until after another restart

**Comment by KJonline** [comment]
> same here, after a restart of HA; all status of lights shows correct, but then any subsequent changes on Hive are not updated in HA... until after another restart

@tmoore22 is this only related to available/unavailable or is your is more detriment than that e.g if you switch the light off in the hive app it doesn’t update in HA?

**Comment by tmoore22** [comment]
> > same here, after a restart of HA; all status of lights shows correct, but then any subsequent changes on Hive are not updated in HA... until after another restart
> 
> @tmoore22 is this only related to available/unavailable or is yours more detriment than that e.g if you switch the light off in the hive app it doesn’t update in HA?

its related to all Light status on/off and online/offline .. nothing is updating in HA when changed on the Hive side, only after restart.

**Comment by KJonline** [comment]
@tmoore22 this issue is related to groups when you say the status doesn’t update is it a grouped light you are referring to?

**Comment by tmoore22** [comment]
All lights, not just the grouped ones..

**Comment by mikebakke** [comment]
Can pretty much confirm this. For me, the only time that the heating controls update at all is during a restart. 
Log entries:


Logger: homeassistant.components.climate
Source: custom_components/hive/climate.py:82
Integration: Climate (documentation, issues)
First occurred: 06:51:48 (2 occurrences)
Last logged: 06:51:48

    Error adding entities for domain climate with platform hive
    Error while setting up hive platform for climate

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 316, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 384, in _async_add_entity
    device_info = entity.device_info
  File "/config/custom_components/hive/climate.py", line 82, in device_info
    "model": self.device["device_data"]["model"],
KeyError: 'model'



Logger: homeassistant.components.sensor
Source: custom_components/hive/sensor.py:85
Integration: Sensor (documentation, issues)
First occurred: 06:51:48 (2 occurrences)
Last logged: 06:51:48

    Error adding entities for domain sensor with platform hive
    Error while setting up hive platform for sensor

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 316, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 427, in _async_add_entity
    original_icon=entity.icon,
  File "/config/custom_components/hive/sensor.py", line 85, in icon
    return icon_for_battery_level(battery_level=self.device["status"]["state"])
KeyError: 'status'

Logger: homeassistant.components.device_tracker
Source: components/device_tracker/legacy.py:256
Integration: Device Tracker (documentation, issues)
First occurred: 06:51:46 (1 occurrences)
Last logged: 06:51:46
Error setting up platform legacy

**Comment by KJonline** [comment]
@tmoore22 what types of hive lights do you have?

@mikebakke what version of the thermostat do you have this version 1 https://mightygadget.co.uk/hive-active-heating-smart-thermostat/  version 2 is the current one

**Comment by mikebakke** [comment]
Hi

I assume it's the latest one - square, smoked perspex front with a physical knob to adjust the target temp.

Rgds

**Comment by tmoore22** [comment]
`I have only Warm White/dimmable, no RGB colour lights... about x15

**Comment by mikebakke** [comment]
fwiw - I have 2 x rgb lights and they do seem to be updating after the 120 seconds - it's just the heating for me.

**Comment by KJonline** [comment]
@tmoore22 sorry if I’m asking the same question again are the individual lights in HA  that  are not updating part of a light group in the hive app?

**Comment by KJonline** [comment]
@mikebakke can you give me more details around your thermostat. Does it have hot water functionality? Is it part of a multi zone? Do you live in the UK?

**Comment by mikebakke** [comment]
I am in the UK. The thermostat does also control hot water - enables schedules and boost. I don't have any zones/valves. Setup is hub with ethernet to router, control box mounted next to boiler and this thermostat connected to wifi on the wall. I have TRVs but they are so unreliable I'm close to rage-quitting with them - actually reverted to a manual TRV for the one in my study this morning. The HA functionality with the stat is still valuable regardless.

Rgds

**Comment by tmoore22** [comment]
> @tmoore22 sorry if I’m asking the same question again are the individual lights in HA that are not updating part of a light group in the hive app?

no, all lights are not updating .. .if they are in a group or not, also single lights not updating

**Comment by nil-ghosh** [comment]
Surprisingly my Hive lights (grouped) are working for me. The status is getting updated. However, the heating - thermostats and hot water (incl. boost and state) sensors aren't updating. The statuses do change only after restarting HA (but not consistent).

**Comment by tmoore22** [comment]
ok .. I removed the groups, restarted HA and the lights are now updating correctly.. on/off and online/offline states

**Comment by KJonline** [comment]
@tmoore22 thanks for confirming this the next release will allow groups to exist in hive but won’t be displayed in HA. Thus shouldn’t impact individual lights

**Comment by tmoore22** [comment]
back with some feedback, still on b25 and the online/offline status of lights is not getting updated :(

Still operating with no Hive Groups, i.e configuration not changed for last couple of weeks..

Only noticed recently but expect this has always been the case. After a restart, the state is updated, but then never again!

**Comment by KJonline** [comment]
Fixed with latest release please reopen if still an issue
