### ISSUE TITLE
B.25 no prompt for credentials [BUG]

### ISSUE THREAD

**Issue by jimmyeao** [Pyhive/HA-Hive-Custom-Component#45]
**Describe the bug**
After removing the built-in Hive integration, and adding the custom b25 component, I was expecting to be prompted for credentials

**To Reproduce**
Steps to reproduce the behaviour:
1. Install b25 - no prompt for username / password is shown

**Expected behaviour**
WOuld be promoted for credentials on installation

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] WIndows 10
 - Browser Chrome
 - Version  86.0.4240.198 

**Additional context**
Hass OS 4.17 Supervisor 2020.12.6

**Comment by KJonline** [comment]
@jimmyeao How are you configuring the integration. Did get chance to look at the README for how to install and setup?

if so at which step are things going wrong for you?

**Comment by jimmyeao** [comment]
Hi,
installed through HACs, I was expecting the integration to prompt for credentials on installation (Step 5)

**Comment by KJonline** [comment]
@jimmyeao it doesn’t prompt for credentials on installation that comes as part of configuration and setup. Which need to be done in the home assistant configuration

**Comment by jimmyeao** [comment]
Understood - have added it to my config yaml, 
just noticed it doesn't use climate.heating now, but does use climate.Receiver1
All seems to be working now, thank you for your patience.

**Comment by KJonline** [comment]
Yes receiver is the name Hive have given it. you can change it in the hive app and that will filter down to ha after a restart.
