### ISSUE TITLE
[BUG]sensor.ZONE_current_temperature and sensor.ZONE_target_temperature `unavailable`

### ISSUE THREAD

**Issue by unlucio** [Pyhive/HA-Hive-Custom-Component#46]
**Describe the bug**
Continuously changing entities values mess up with my system

**To Reproduce**
1. Go to 'developer-tools/state'
2. Search for 'current_temperature'
3. Verify the current state is "unavailable"
4. Repeat for target_temperature

**Expected behavior**
I'd expect to have the current values for current_temperature temperature unavailable.
Most of all I'd expect this plugin to stop keep changing `entity id` with every new release as this is annoyingly messing up with my automation, statistics, monitoring, and AI.

**Screenshots**
missing values:
<img width="1089" alt="Screenshot 2020-12-10 at 12 06 36" src="https://user-images.githubusercontent.com/778799/101764831-d1179100-3ae0-11eb-9b0a-de1e2b002c62.png">

those values are now apparently kin a totally different entitity
<img width="976" alt="Screenshot 2020-12-10 at 12 07 00" src="https://user-images.githubusercontent.com/778799/101764873-e1c80700-3ae0-11eb-9b2a-95ca4c0e3d4d.png">

all my temperature data since I updated to the latest beta are missing.
<img width="1695" alt="Screenshot 2020-12-10 at 12 04 41" src="https://user-images.githubusercontent.com/778799/101764813-cceb7380-3ae0-11eb-9793-b740a9f85a4a.png">

**Desktop (please complete the following information):**
 - OS: bigSur 11.0.1 (20B29)
 - Chrome
 - Browser Version 87.0.4280.88 (Official Build) (x86_64)

**Comment by niven01** [comment]
+1

**Comment by KJonline** [comment]
Are you configuring it via YAML or via the UI?

**Comment by Hawke3y3** [comment]
I entered the creds into configuration.yaml

I am trying to configure Hive via the UI - I didn’t know this could be done
via YAML

**Comment by KJonline** [comment]
Setting up via yaml won’t show the additional sensors it will only show if you set it up via the UI

**Comment by Hawke3y3** [comment]
So you are saying it is better to remove the credentials from the config
yaml and set the credentials in the UI? I haven’t been prompted to do so
before in the UI.

Hive isn’t appearing anywhere but the HACS interface...

**Comment by Hawke3y3** [comment]
I have just seen where to install the BETA, HIVE is now appearing in
configuration. Just adjusting the configuration.yaml now and will configure
via the UI....

**Comment by KJonline** [comment]
You don’t need the configuration yaml if you are configuring via the UI

**Comment by Hawke3y3** [comment]
Up and running! Sorry if I have semi wasted your time, I’ve wanted to dive
into this for a while now and I’m glad I’ve got it up!

Next is to figure out Nest integration once I’ve cleaned up Hive!

Thanks for your guidance.

**Comment by KJonline** [comment]
Issue closed
