### ISSUE TITLE
[BUG] Hive not showing in INTEGRATIONS post HACS install

### ISSUE THREAD

**Issue by Hawke3y3** [Pyhive/HA-Hive-Custom-Component#48]
Home Assistant 2020.12.1 installed via Docker, Container Managed with Portainer 

I have HACS Installed --> Hive not showing in search field in CONFIGURATION > INTEGRATIONS > +INTEGRATION

I have input my credentials, username/password as described into the configuration.yaml file. I do not have 2FA enabled, and I have triple checked my credentials are correct!

I can see the hive folder has been added to 'custom_components' 

**Expected behaviour**
I expected after following instructions for 'Hive' to be presented as an integration, which would then login / pull devices and services etc. In developer tools I cannot see the services i.e 'climate.heating'

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 64-bit
 - Processor: ARMv8 Processor rev 1 (v8l) x4
 - GPU: NVIDIA Tegra X1
 - Browser: Chromium 87.0.4280.66 (Official Build) Built on Ubuntu

I hope this is enough information, please let me know if I need to provide anything further in order to fix!

Thanks

**Comment by KJonline** [comment]
@Hawke3y3 I just wanted to double check what version you have got installed it is 2020.1 beta 25?

**Comment by Hawke3y3** [comment]
@KJonline This is what I have installed:

Home Assistant 2020.12.1

Frontend version: 20201212.0 - latest

HACS is 1.9.0

**Comment by stanfordcg** [comment]
same problem. v 2.3.3, HACS 1.9.0,  HA 0020.12.1

**Comment by Hawke3y3** [comment]
Try selecting the latest version when setting up the integration in HACS
Worked for me...

**Comment by stanfordcg** [comment]
thanks, b25 fixed it for me.

**Comment by KJonline** [comment]
Closing this issue as it not a issue in this integration
