### ISSUE TITLE
[BUG] sensor.hive_hub_status not available

### ISSUE THREAD

**Issue by perjury** [Pyhive/HA-Hive-Custom-Component#50]
**Describe the bug**
sensor.hive_hub_status not available

**Expected behaviour**
sensor.hive_hub_status should report status as per https://www.home-assistant.io/integrations/hive/#sensor

Using b25

**Comment by KJonline** [comment]
Fixed in latest release

**Comment by perjury** [comment]
Still an issue in latest release

**Comment by KJonline** [comment]
Do you have an example and some details around what hub you have?

**Comment by perjury** [comment]
Oops. Looked again and looks like I was using an older version of the sensor name. I see it now.
