### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by mattman73** [Pyhive/HA-Hive-Custom-Component#53]
**Describe the bug**
I have added the custom component via HACS and restart HA, when searching integration 'Hive' is not listed and if I manually add the info to the configuration.yaml file the integration still is not working.

**To Reproduce**
Steps to reproduce the behaviour:
1. added Hive custom component via HACS version 
2. Restarted HA.
3. Go to 
 Navigate to the Home Assistant Configuration.
 Open the integrations panel.
 Click the add integrations option
 Search for Hive - here is the issue as Hive does not appear in the list

**Expected behaviour**
I would have like to see the hive to follow the 2FA verification as this is the only difference with Hive from when I had it working before.

**Screenshots**
[https://1drv.ms/u/s!AmQePyx9R1BXh65PbGYmrTeva6m3Ow?e=KEH50j](url)

**Desktop (please complete the following information):**
 - OS: Fedora 27 running Docker 19.0.3
 - H A Supervisor Version 2020.12.7
 - Browser Chrome

**Additional context**
I have also tried adding the hive info manually add the info to the configuration.yaml this was working before the changes to login hive website.

**Comment by KJonline** [comment]
@mattman73 have you tried clearing your browser cache and session cookies this is sometimes the issue with Hive not appearing in the list.

**Comment by mattman73** [comment]
@KJonline I did and now it is showing in the list, maybe you could update the read me and add this point in. 
Many thanks for your help.
Matt
