### ISSUE TITLE
Min/Max attributes for sensor.*_current_temperature are incorrect

### ISSUE THREAD

**Issue by perjury** [Pyhive/HA-Hive-Custom-Component#55]
**Describe the bug**
The 'Today Min/Max' and 'Restart Min/Max' attributes are incorrect

**To Reproduce**
View attributes via Developer Tools

**Expected behaviour**
Expect to see correct min/max values

**Screenshots**
You can see from the screenshot that the min and max values for 'today min/max' values are identical in all cases
You can see from the screenshot that in some instances the min value shown is greater than the current value.

(Incidentally, Current, Target and Difference temps ONLY show if the  *_heat_heating_state is ON. They do not show if OFF. Is this as intended?)

![Developer-Tools-Home-Assistant](https://user-images.githubusercontent.com/11613248/104924556-83226280-5995-11eb-8a13-e7e6e9631dd7.png)

**Comment by KJonline** [comment]
Fixed with latest release please reopen if still an issue

**Comment by perjury** [comment]
This is still an issue in the latest release
Looking more closely, the Today Min / Max values reported are identical and it looks like it's showing the Max temperature today for both.

**Comment by perjury** [comment]
@KJonline I would re-open this issue if I could but I can't for the life of me see how!

**Comment by KJonline** [comment]
Fixed in 2021.3.1
