### ISSUE TITLE
Hive Integration not showing in Configuration\integrations[BUG]

### ISSUE THREAD

**Issue by gshoebridge** [Pyhive/HA-Hive-Custom-Component#56]
Hivce stopped working

uninstalled and deleted everything (HACS and Config and remmed out the credentials in yaml

restarted 

Since then - the configuration\integration of Hive does not exist. 

instructions as per latest version - install via HACS then install from Config\Integrations.

**Comment by Pennarddog** [comment]
I have the exact same issue

**Comment by Pennarddog** [comment]
Uninstalled via HACS then installed 2020.1_b25 and it fixed the issue

**Comment by KJonline** [comment]
This isn’t a bug with this component, please try clearing browser cache and restarting the host machine.
