### ISSUE TITLE
2 Hive Hubs

### ISSUE THREAD

**Issue by jghsmith** [Pyhive/HA-Hive-Custom-Component#60]
I have 2 Hive Hubs in separate properties each with its own Hive account. Is it possible to use both with this component? If so how?

**Comment by dougle03** [comment]
Most integrations allow multiple instances. Add one of your Hive accounts, then add the second one. It'll be the quickest way to find out

**Comment by KJonline** [comment]
The backend currently doesn’t support multiple accounts but it’s something we are planning in the future.

**Comment by KJonline** [comment]
Fixed in 2021.3.0
