### ISSUE TITLE
History Graphs

### ISSUE THREAD

**Issue by trickyg719** [Pyhive/HA-Hive-Custom-Component#62]
I am trying to setup a History Sensor so that I can monitor how long the heating is on for over the day.

I have added the following but I only seem to get data when state is set to "heat" - However this is just gives a value of 24 hours so assume must be the default state. Does anyone know what the state should be set to to monitor when the heating is on?

  #  History
sensor:
 - platform: history_stats
   name: Heating On Today
   entity_id: climate.receiver_1
   state: 'On'
   type: time
   start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
   end: '{{ now() }}'
 - platform: history_stats
   name: Heating On Yesterday
   entity_id: climate.receiver_1
   state: 'On'
   type: time
   end: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
   duration:
     hours: 24

**Comment by KJonline** [comment]
This needs posting on the community forum, this is not a code issue. Please post here but the issue seems to be your are looking at the state and for the climate device you should look at the hvac_action attribute as this determines when the heat is on or off.
