### ISSUE TITLE
Hi installed via HACS but not showing as an intergration?

### ISSUE THREAD

**Issue by privateak** [Pyhive/HA-Hive-Custom-Component#63]
Hi all- Noob here, installed the Hive add on but I cannot add it as an intergration?

**Comment by KJonline** [comment]
@privateak Have you tried restarting and clearing your browser cache?

**Comment by KJonline** [comment]
This is not a code issue

**Comment by privateak** [comment]
> Hi all- Noob here, installed the Hive add on but I cannot add it as an intergration?

Thanks, all working now.
