### ISSUE TITLE
[BUG] Hot water sensors missing

### ISSUE THREAD

**Issue by EvBooKY** [Pyhive/HA-Hive-Custom-Component#65]
**Describe the bug**
Previously in beta 25, there were a number of sensors holding hot water information. These appear to be missing in 2021.2.

**To Reproduce**
Steps to reproduce the behaviour:
1. View Entities
3. Also in Developer Tools | States
4. search for boost ends in. 
5. This finds the Heating (with a slightly different name to previous but easily fixed)
6. No Hot water entity is found

**Expected behaviour**
Hot water has sensors, mode, boost and state with a few attributes such as boost ends in etc.

**Screenshots**
![image](https://user-images.githubusercontent.com/65856607/108632422-c1b0ae80-7466-11eb-9ff4-e362a3c88359.png)

Desktop (please complete the following information):

OS: Windows 10
Browser: Chrome
Version : 88.0.4324.182

**Comment by KJonline** [comment]
there has been name changes with this release is it under a different name?

**Comment by EvBooKY** [comment]
No that I can see. This is the only entity from Hive with the word state in it. 

![image](https://user-images.githubusercontent.com/65856607/108633346-ac8a4e80-746b-11eb-94e8-1e85cd5db017.png)
Not sure why that Radiator Value is okay and all the other ones (I've another 4) that don't. It appears hot water and heating have also lost state.
