### ISSUE TITLE
Unable to get the integration working [BUG]

### ISSUE THREAD

**Issue by Demon-Angelz** [Pyhive/HA-Hive-Custom-Component#81]
Hi!
So, I set up HACS with version the Hive Custom Component  v2021.4.0
This version, when selecting to install the Hive integration it states it is unable to open config flow.

After this, I tried reinstalling HCC but with v2021.3.1, this version worked fine and would allow me to add the integration and sign in and authenticate, but would cause it to send auth requests at spam (I saw this on here as being an issue from that version)

Now back on v2021.4.0, It shows the integration still there, as it successfully installed with v2021.3.1, but I have the following errors upon restating Home Assistant:

> Logger: homeassistant.config_entries
> Source: config_entries.py:563
> First occurred: 18:47:47 (1 occurrences)
> Last logged: 18:47:47
> 
> Error occurred loading configuration flow for integration hive: No module named 'homeassistant.components.hive.const

> Logger: homeassistant.setup
> Source: setup.py:138
> First occurred: 18:45:25 (1 occurrences)
> Last logged: 18:45:25
> 
> Setup failed for hive: Unable to import component: No module named 'homeassistant.components.hive.const'

**Comment by KJonline** [comment]
@Demon-Angelz is this fixed for you now?
