### ISSUE TITLE
Hive component fails to start following update to 21.4.0

### ISSUE THREAD

**Issue by edseymour** [Pyhive/HA-Hive-Custom-Component#86]
Homeassistant log reports: ```Setup failed for hive: Unable to import component: No module named 'homeassistant.components.hive.const'```

Hive installed via HACS with this issue appearing after updating to 21.4.0
Have tried reinstalling, uninstalling and installing earlier version (21.3.1), and manually installing

**Comment by KJonline** [comment]
@edseymour what version of home assistant are you on?

**Comment by edseymour** [comment]
## System Health

version | core-2021.3.4
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.7
os_name | Linux
os_version | 4.19.0-16-amd64
arch | x86_64
timezone | Europe/London

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4914
Installed Version | 1.11.3
Stage | running
Available Repositories | 776
Installed Repositories | 6

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Debian GNU/Linux 10 (buster)
-- | --
update_channel | stable
supervisor_version | supervisor-2021.04.0
docker_version | 20.10.5
disk_total | 58.5 GB
disk_used | 3.8 GB
healthy | true
supported | true
supervisor_api | ok
version_api | ok
installed_addons | Check Home Assistant configuration (3.6.0), Let's Encrypt (4.11.0), NGINX Home Assistant SSL proxy (3.0.1)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 0
views | 3
mode | storage

</details>

**Comment by KJonline** [comment]
@edseymour for the latest version to work you need to be on home assistant version 2021.4.0 or greater.
